// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaeyfjkymzbivfogfibw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZXlmamt5bXpiaXZmb2dmaWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzQ1NTMsImV4cCI6MjA2MzYxMDU1M30.PA594P2mPB7kWF-wjKSqJu_aX51c30wqq7ZSLiR81xA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);